In [2]:
import pandas as pd 
from sklearn.metrics import accuracy_score , precision_score , recall_score , f1_score 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier

In [3]:
heart_df = pd.read_csv("../datasets/1-heart.csv")

In [4]:
heart_df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [5]:
X  = heart_df.drop(["target"] , axis = 1)
y = heart_df["target"]

X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [6]:
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [7]:
# train test split 

X_train , X_test , y_train , y_test = train_test_split(
  X , y , random_state=42 , test_size=0.2
)

In [10]:
# scaling 
scaler = StandardScaler()
X_train_scaler = scaler.fit_transform(X_train)
X_test_scaler = scaler.transform( X_test)

In [15]:
knn_classifier = KNeighborsClassifier(n_neighbors=5)
knn_classifier.fit(X_train_scaler , y_train)

y_pred = knn_classifier.predict(X_test_scaler)

print("recall score: ", recall_score(y_test, y_pred))
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("precision score: ", precision_score(y_test, y_pred))

recall score:  0.875
accuracy score:  0.9016393442622951
precision score:  0.9333333333333333

In [16]:
knn_classifier = KNeighborsClassifier(n_neighbors=3)
knn_classifier.fit(X_train_scaler , y_train)

y_pred = knn_classifier.predict(X_test_scaler)

print("recall score: ", recall_score(y_test, y_pred))
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("precision score: ", precision_score(y_test, y_pred))

recall score:  0.78125
accuracy score:  0.8524590163934426
precision score:  0.9259259259259259

In [ ]:
# n=7 - best score till now 
knn_classifier = KNeighborsClassifier(n_neighbors = 7)
knn_classifier.fit(X_train_scaler , y_train)

y_pred = knn_classifier.predict(X_test_scaler)

print("recall score: ", recall_score(y_test, y_pred))
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("precision score: ", precision_score(y_test, y_pred))

recall score:  0.90625
accuracy score:  0.9180327868852459
precision score:  0.9354838709677419

In [19]:
knn_classifier = KNeighborsClassifier(n_neighbors = 9)
knn_classifier.fit(X_train_scaler , y_train)

y_pred = knn_classifier.predict(X_test_scaler)

print("recall score: ", recall_score(y_test, y_pred))
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("precision score: ", precision_score(y_test, y_pred))

recall score:  0.875
accuracy score:  0.9016393442622951
precision score:  0.9333333333333333

In [20]:
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier

classifier = KNeighborsClassifier()

# Dictionary syntax: {key: [values]}
param_grid = {"n_neighbors": [3, 5, 7, 9]}  # Fixed typo & syntax

# Instantiate GridSearchCV properly (add parentheses and pass arguments)
classifierCV = GridSearchCV(
    classifier,
    param_grid,
    cv=5,
    scoring="recall"
)

classifierCV.fit(X_train_scaler, y_train)

y_pred = classifierCV.predict(X_test_scaler)

print("recall score: ", recall_score(y_test, y_pred))
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("precision score: ", precision_score(y_test, y_pred))

# Bonus: See best parameters found
print("Best n_neighbors:", classifierCV.best_params_)
print("Best CV score:", classifierCV.best_score_)

recall score:  0.90625
accuracy score:  0.9180327868852459
precision score:  0.9354838709677419
Best n_neighbors: {'n_neighbors': 7}
Best CV score: 0.8717948717948717

"Pipelines chain preprocessing and modeling steps together, preventing data leakage by ensuring transformations (like scaling) are fitted only on training data and applied consistently to test data."

In [21]:
#pipeline 

from sklearn.pipeline import Pipeline

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline = Pipeline([

    ('scaler' , StandardScaler()) ,
    ('knn'  , KNeighborsClassifier() )
])

param_grid = {"knn__n_neighbors": [3, 5, 7, 9]}

classifierCV = GridSearchCV(
    pipeline,
    param_grid,
    cv=5,
    scoring="recall"
)

classifierCV.fit(X_train, y_train)

y_pred = classifierCV.predict(X_test)

print("recall score: ", recall_score(y_test, y_pred))
print("accuracy score: ", accuracy_score(y_test, y_pred))
print("precision score: ", precision_score(y_test, y_pred))

print(classifierCV.best_params_)

recall score:  0.90625
accuracy score:  0.9180327868852459
precision score:  0.9354838709677419
{'knn__n_neighbors': 7}